environment:
  development:  %localhost%
  production: 

paths:
  controllers: controllers/
  models:      models/
  templates:   templates/
  views:       views/
  partials:    partials/

routes:
  page: 