url: localhost/whats-our-plan/

parameters:
  database_host:     localhost
  database_name:     whatstheplan
  database_user:     root
  database_password: 

  mailer_transport:  smtp
  mailer_host:       localhost